spring.application.name=todolist
# db
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/mvc?createDatabaseIfNotExist=true
spring.datasource.username=springtuto
spring.datasource.password=jaimeleveau
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# jpa/hib
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always

# devtools
spring.devtools.livereload.enabled=true

# errors
server.error.whitelabel.enabled=false